#!/usr/bin/env bash
# install nginx web server

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart